- name:  playbook
  hosts:  web_servers
  tasks:
    - name: first_task
      apt:
        update_cache: true

    - name: second_task
      apt:
        name: nginx
        state: latest

    - name: third_task
      copy:
        src: ~/index.html
        dest: /var/www/html/index.html

    - name: fourth_task
      service:
        name: nginx
        state: restarted